### ISSUE TITLE
Using StartContainerExecAsync for capturing stream output

### ISSUE THREAD

**Issue by skarred14** [Microsoft/Docker.DotNet#100]
I am using the 2.124 version of the API. The objective of the problem is to exec into a running container by passing in a command to print text to console and extract the same back using the stream output. Below is the code snippet. The startcontainerexec returns a reponse 200 - status:OK, but the stream parameters Length, Seek, etc. are not populated.  I was able to extract the logs in case I started a container with an entrypoint command to keep the container running - for example, running a httpd server on the container and using docker logs. Although this is great, it doesnt solve the purpose of exec at any time into a running container and extracting the output on console.  Any suggestions as to how an exec can be done using the API to get a streamed output back either through docker logs or a different spec of the exec from the one below?
Code:
private IList<ContainerListResponse> = new IList<ContainerListResponse>();
public async Task<IList<ContainerListResponse>> list_containers()
        {
            var dockerConfiguration = new DockerClientConfiguration(this.uri);
            DockerClient client = dockerConfiguration.CreateClient();
                        this.containers_list = await client.Containers.ListContainersAsync(new ContainersListParameters()
            {
                All = true
            });
            IEnumerable<string> names = (from l in this.containers_list select l.Names.First());
            string id = this.containers_list[0].ID;
            ContainerExecCreateResponse c = await client.Containers.ExecCreateContainerAsync(id, new    ContainerExecCreateParameters()
            {
                Detach = false,
                Tty = false,
                Cmd = new List<string>() { "ls" }
            });
            await client.Containers.StartContainerExecAsync(c.ID, CancellationToken.None);
            do
            {
                var l = await client.Containers.GetContainerLogsAsync(id, new ContainerLogsParameters()
                {
                    ShowStderr = true,
                    ShowStdout = true,
                }, CancellationToken.None);
                Regex r = new Regex(@"hello");
                Match m = r.Match(l.ToString());
                if (m.Success)
                {
                    string h = m.Groups[1].Value;
                    break;
                }
            } while (true);
                return this.containers_list;
        }

**Comment by jterry75** [comment]
@jstarks - It looks like `StartContainerExecAsync` has hard coded `Detach = true` in the function. Would you expect by passing `false` to that we should return a `MultiplexedStream`?

**Comment by jstarks** [comment]
If you want the stream, you have to use `StartAndAttachContainerExecAsync`, which does return a `MultiplexedStream`.

**Comment by skarred14** [comment]
Got it! I have just been using the StartAndAttachContainerExecAsync. The response reads Status: 200, but I am trying to figure out how I could read the stream using ReadOutputAsync(). Any suggestions/examples on how I could retrieve the buffer, offset and count?
MultiplexedStream x = await client.Containers.StartAndAttachContainerExecAsync(c.ID, false, CancellationToken.None);
MultiplexedStream.ReadResult = await x.ReadOutputAsync();

**Comment by jterry75** [comment]
You cant `get the offset and count`. That doesnt make sense on a stream. For a few reasons but mostly because we dont know the `length` of a stream because it can always send more data. You need to just read from the stream all available data until the `stdout` and `stderr` pipes are closed in which case you have all the data. As far as `offset` this is a client local property. IE: Where to start reading into/from. Does that make sense?

**Comment by jstarks** [comment]
jterry75 is right, we don't get a seekable stream from Docker.

I suggest either using `MultiplexedStream.CopyOutputToAsync`, or take a look at that function's implementation to see how you can use `MultiplexedStream.ReadOutputAsync`. Basically you have to read in chunks, see if the chunk was for stdin, stdout, or stderr, and react appropriately (stdin doesn't make sense since it should be a writable stream only, but the Docker API claims to support it). In your use case, you might just want to use `CopyOutputToAsync` to copy into a `MemoryStream` -- you can use the same stream for all three parameters to combine the three streams.

**Comment by jterry75** [comment]
@skarred14 - Please reopen if you have any other unanswered questions on this topic. Otherwise closing this.
