### ISSUE TITLE
Add Swarm, Services, and Node models for Docker v1.12.0

### ISSUE THREAD

**Issue by jterry75** [Microsoft/Docker.DotNet#119]
In order to support the Docker Swarm scenarios we should have the model generator output Swarm, Services, and Node models so that we can add endpoints for those services as well.

**Comment by jterry75** [comment]
@jstarks, @swernli - What do you guys think about this? Should we introduce another dll for Docker.Swarm or put this into Docker.DotNet?

**Comment by stefanprodan** [comment]
I would use Docker.DotNet dll since Swarm mode info is part of [SystemInfoResponse](https://github.com/Microsoft/Docker.DotNet/blob/master/Docker.DotNet/Models/SystemInfoResponse.Generated.cs#L160). I would also rename [Info class](https://github.com/Microsoft/Docker.DotNet/blob/master/Docker.DotNet/Models/Info.Generated.cs) to SwarmInfo.
