### ISSUE TITLE
Un-gate cert support when .NETcore updates

### ISSUE THREAD

**Issue by swernli** [Microsoft/Docker.DotNet#132]
Once the new .NET core comes out with support for the rest of X509Certificate2 (namely, settable PrivateKey) we should remove the NET46 gating around the TLS support.

**Comment by shairozan** [comment]
Are there any plans to implement TLS Auth for clients? It's a major blocker for me using .Net for a major project I have.

**Comment by jterry75** [comment]
This was originally only an issue for `.NET Core`. Are you using `.NET` or `.NET Core`? If it is `.NET Core` you need this for I can prioritize looking to see if we have what we need in the runtime by now to make these fixes.

**Comment by shairozan** [comment]
We're using .Net Core.

**Comment by jterry75** [comment]
So I took a look. The issue is that .netstandard1.6 (1.6.1) does not include the entire set of `X509Certificate2` properties needed to construct a pub/priv pair from PEM files. However, you could be using certs today if you are running on Windows and can use PFX files rather than PEM files to store the key. Then when your application runs you can you just need to load the key from the PFX file path via `RSAUtil`.cs or just construct your `X509Certificate2` yourself. Will either of those options work for you?

**Comment by mvreg** [comment]
Now that dotnet core 2.0  is released...   Is it possible to use certificate based authentication to remote docker daemon from linux .net core 2.0 app? 
I have seen in https://stackoverflow.com/questions/44465574/net-standard-merge-a-certificate-and-a-private-key-into-a-pfx-file-programma  that some support for PrivateKey was added.

**Comment by jterry75** [comment]
Ah I forgot to reference this. Yes as of #268 this should now work. Please give it a shot! If it doesn't work please reopen.
