### ISSUE TITLE
[Question] Example of Filters parameter for ListImagesAsync method

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/Docker.DotNet#137]
Could you point me to some examples using the Filters in ListImagesAsync method?  I can reference the docs (https://docs.docker.com/engine/reference/commandline/images/), but trying to understand how it is actually coded with the API.

For example, what would it look like to query **before** a specific image?

Thanks in advance.

**Comment by jterry75** [comment]
@shaggygi - Unfortunately for `images` specifically you cant filter on the same things you can for a container. If you take a look at: [Image.go](https://github.com/docker/docker/blob/master/daemon/images.go) `acceptedImageFilterTags` you can see that you can only `filter` based on `dangling, label, before, since, reference`. You cant do something like `filter name=test`. Hope that helps

**Comment by shaggygi** [comment]
@jterry75  thanks for response.  Those are the types I was looking for examples using with the API.  In the image parameter, it includes All, Filters and MatchName.  How would I define the image parameter Filters for something like the **before** type?  

before (<image-name>[:<tag>], <image id> or <image@digest>) - filters images created before given id or references

**Comment by jterry75** [comment]
Oh ok cool. Yet another dockerism that I truly dont understand but can tell you how to use. :). The dictionary needs to be `key, value, true`. I believe that somewhere in the world of Docker this was programmed so that one day they could do a negative filter but today all that is accepted is true. So as an example:

```C#
var before = "<id>";
Filters = new Dictionary<string, IDictionary<string, bool>> 
{  
    {"before", new Dictionary<string, bool>
        { 
            {before, true} 
        }
    }
}
```

**Comment by shaggygi** [comment]
Got it.  I will try these out tonight.  Thanks again.
