### ISSUE TITLE
InspectContainerAsync throws parsing error

### ISSUE THREAD

**Issue by pauldotknopf** [Microsoft/Docker.DotNet#177]
```
JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IList`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.

Path 'Config.Volumes./home', line 1, position 3361.
```

```c#
var client = new DockerClientConfiguration(new Uri("http://192.168.4.90:4243"))
        .CreateClient();
        
var containers = await client.Containers.ListContainersAsync(new ContainersListParameters());
        
foreach (var container in containers)
{
    // error gets thrown here
    var inspect = await client.Containers.InspectContainerAsync(container.ID);
}
```

![image](https://cloud.githubusercontent.com/assets/523150/23262710/a8ea8ff6-f9a9-11e6-8d73-d618ed705546.png)

**Comment by jterry75** [comment]
I cant quite tell from your error. Is this failing when parsing config.Volumes?

**Comment by jterry75** [comment]
@robborden - How were you testing this? As far as I can tell the latest docker doesnt even use the Volumes entry and this is always returned as `Volumes:null`. This seems to be removed in favor of the HostConfig mount points. 

As an aside I think the correct fix is to create
```C#
struct Empty
{
}

class Config
{
//...
IDictionary<string, Empty> Volumes
// ...
)
```

It appears that although the go code only considers the keys on create on inspect it could potentially write
```json
Volumes: {
  "c:\test": {},
  "c:\test2": {}
}
```
Which is why we are failing at deserialize even though the actual struct contains no properties. 

Will submit a PR for this.

**Comment by jterry75** [comment]
What to take a look at the PR and give me a review?

**Comment by robborden** [comment]
This is possibly not even worth me explaining at this point but I'll do it anyways.  First of all, after i posted before I realized the code I had committed and linked you to was incorrect.  I should have updated the other ticket: https://github.com/coinigy/Docker.DotNet/commit/bb30aea9d7db6f2184e4e0cf93e48e9c0a8a8e54

To summarize, the collection object I settled on for Volumes was Dictionary<string,dynamic> whereas you used Dictionary<string, Empty> which I had no idea even existed, but seems like an even better option.

 You are correct with regards to HostConfig mount points and Volumes from my experience.  Since I confused the above commit, it will possibly make more sense to you now that I had trouble serializing the Volumes property when its type was KeyValuePair<string,string>.  As I type this message to you I realize that it would have at the very least needed to be List<KeyValuePair<string,string>> which explains the serialization errors I encountered during 'create'.

I will take a  look at your PR now.
