### ISSUE TITLE
Add Named Pipe option to DockerClientConfiguration

### ISSUE THREAD

**Issue by ogreenz** [Microsoft/Docker.DotNet#194]
It seems that remote api is not enabled for docker for windows (#109). Since at least for me socat didn't much work for Win10 and I ended up using "Named Pipe TCP Proxy" to get the client working, I think it's rather unnecessarily complicated. we should have something along the line like this:

```
DockerClient dockerClient = new DockerClientConfiguration(new NamedPipeClientStream(".", "docker_engine", PipeDirection.In));


```

**Comment by jterry75** [comment]
We don't control how the Docker for Windows connects in the guest. If it was to connect via tcp then it would be remotely addressable without any proxy mappings. You can already connect via a named pipe stream via Docker.DotNet its just that the client on the 'host' and the daemon in the 'guest' are not on the same 'os' to my knowledge. I believe this would be a change to Docker for Windows not Docker.DotNet.

Am I missing something?

**Comment by ogreenz** [comment]
>  You can already connect via a named pipe stream via Docker.DotNet its just that the client on the 'host' and the daemon in the 'guest' are not on the same 'os' to my knowledge.

I'm not sure what you meant here. First, looking at the code I'm not saying a way to connect to initialize a DockerClient object via a named pipe stream. Second I didn't quite follow the 'os' and on the client and daemon - do you mean different versions of windows on containers on windows host? or linux containers on windows host? or the same thing just on linux hosts?

**Comment by jterry75** [comment]
The URI you pass to the client configuration dynamically chooses the base stream. So passing:
`npipe://./...` will and calling `CreateClient()` will create a `NamedPipeClientStream` in the `DockerClient`. We don't expose it directly but we allow you to do this via the URI passed. If you wanted TCP you could do `tcp://localhost:4589` to connect.

`Docker for Windows` (note this is a product it is not the same as `Docker` on Windows) runs in a Linux VM on a Windows host. So the reason that the 2nd level redirection is needed is because you are exposing the connection outside of the VM if I remember correctly. If you didnt want this 2nd level redirection you would need to run the `Docker` daemon (in the VM) with `-m tcp://...` and open that tcp port on the VM. Then from any host (including the hosting computer) you could use a `DockerClientConfiguration(tcp://<ip-of-vm>:<port>)` URI to get to the `Docker` daemon. Make sense?

**Comment by ogreenz** [comment]
> The URI you pass to the client configuration dynamically chooses the base stream. So passing:
npipe://./... will and calling CreateClient() will create a NamedPipeClientStream in the DockerClient. We don't expose it directly but we allow you to do this via the URI passed. If you wanted TCP you could do tcp://localhost:4589 to connect.

I wasn't aware that was even possible! that's exactly what I was looking for. I do believe it should be mentioned on the README though as an additional way of creating the DockerClient object on Windows.
Regarding `Docker for windows` I think what you said applies for Linux containers running on a windows host, because if I switch to `Windows containers` then that VM you were talking about it switch to off on my system. Regardless I think the matter is closed - thank you for your help!
