### ISSUE TITLE
Dispose DockerClient should also dispose HttpClient

### ISSUE THREAD

**Issue by 303248153** [Microsoft/Docker.DotNet#232]
This code will cause "An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full" error when it runs a while, use `netstat` can confirm local ports are run out.

``` c#
public async Task StartKeepaliveLoop()
{
    while (true)
    {
        using (var client = dockerClientConfiguration.CreateClient())
        {
            await client.Miscellaneous.GetVersionAsync();
        }
        await Task.Delay(1000);
    }
}
```

I known client should be singleton and I already make it, but this code shouldn't cause problem, I think dispose DockerClient should also dispose it's internal HttpClient.

**Comment by Kagamine** [comment]
@galvesribeiro

**Comment by galvesribeiro** [comment]
For both cases, it doesn't matter if you call `.Dispose()`. It will not close the ports. 

That would not throw an issue:

```csharp
public async Task StartKeepaliveLoop()
{
    while (true)
    {
        await client.Miscellaneous.GetVersionAsync();
        await Task.Delay(1000);
    }
}
```

However, I don't understand why you are doing that... KeepAlive settings are available since the `HttpClient` itself is exposed in DockerClient class.

I know that people tend to use `using()` blocks to whatever implements `IDisposable`. However, This is not a good idea with the current `HttpClient` implementation. There is a big discussion here regarding the current API design and how will we tackle that in the future: https://github.com/dotnet/corefx/issues/21568#issuecomment-315909052

For now, I would recommend to reuse `DockerClient` the same way you would reuse `HttpClient`.

**Comment by 303248153** [comment]
I agree DockerClient should be singleton, but the problem isn't that.
The following discussion should be in #233 , I'm just close this issue.
