### ISSUE TITLE
Stream Length property unavailable from MultiplexedStream

### ISSUE THREAD

**Issue by aemery** [Microsoft/Docker.DotNet#264]
**What version of Docker.DotNet?:**

```
Tip
```

EDIT 2: tl;dr StartContainerExecAsync that returns the body of the API response and with a parameter to set detach to false is all I need. Sorry for the double edit, should have dug a little more before opening the issue.

This is more of an "ease of use" request.

The MultiplexedStream class, used to get the output of /exec/{id}/start, does not expose the Length property of the internal _stream object. When calling ReadOutputAsync, an arbitrary number must be given as count. Passing something like multiplexedStream.Length would make more sense IMO.

An overloaded method with only buffer and cancellationToken as parameters could also be exposed by MultiplexedStream. In there, offset and count could be set internally to 0 and _stream.Length since this is the typical use case.

In any way, this is not a deal breaker, feel free to give me your opinion on this issue.

EDIT: Digging around in the SDK, I realized that simply having access to the body of the response to "/exec/{id}/start" as a string would cover my use case since I only need to get the output of a PowerShell command. i.e.

**Comment by jterry75** [comment]
I'm not sure I fully understand. In the "attached" case how would you know the length? I am almost certain that even if we exposed the length it would throw because the actual stream doesn't know the answer. The concept here is that you can get any length of output. So it might take multiple buffered reads to get the full output.

Are you saying that you would like one full "Read to end and assign it to a string" method so that its just easier than having to do the reads yourself?

**Comment by aemery** [comment]
Yep, exactly. I need a simple way to call a command on a Docker and get the complete output.
