### ISSUE TITLE
Some of the timeout style properties should be TimeSpan

### ISSUE THREAD

**Issue by jterry75** [Microsoft/Docker.DotNet#98]
For example:

`Config.StopTimeout`
`HealthConfig.Interval`
`HealthConfig.Timeout`
etc.

This will require us to implement custom JsonConverters for TimeSpan but because sometimes the result is in Seconds and in others its NanoSeconds we likely need to introduce an attribute that describes the destination conversion expected.

**Comment by jasoncouture** [comment]
Just a comment on this rather than opening a new issue:
the underlying HttpClient timeout should be exposed, there are numerous situations where it would be highly helpful to be able to change the default timeout of 100 seconds.

client.RequestTimeout or configuration.RequestTimeout are a few suggestions.

**Comment by jterry75** [comment]
@jasoncouture - Actually these arent the same type of "timeout" issue. Can you open a new issue for this so we can track it independently?

**Comment by jasoncouture** [comment]
@jterry75 Sorry for the late response, Sure thing.

**Comment by orthros** [comment]
So I've got a rough draft of this working, though it is untested.

specgen is now outputting certain types to ```TimeSpan?``` and you can specify on a per-property basis custom Attributes to decorate the property with.

On the json serialization of ```TimeSpan``` attributes: would it be better to decorate the Property with the "standard" ```[JsonConvert(Type converterType)]``` style, or to put in a ```IContractResolver``` and custom ```Attributes``` on the Properties to denote what should be serialized to/from seconds/nanoseconds? 

I have it working both ways, but prefer the custom attributes path to help keep the consuming code clean.

**Comment by jasoncouture** [comment]
@orthros, 
Just my $0.02, I think the attribute is the better choice, because if we ever needed to change the contract resolver for something else it would be a headache. (I'm not a member of this project, it's just my opinion.)

**Comment by orthros** [comment]
@jasoncouture thanks for the feedback! In my PR (#205 ), I wound up going with a single attribute that you can decorate with a Seconds or Nanoseconds enumeration like so

```csharp
[DataMember(Name = "Timeout", EmitDefaultValue = false)]
[TimeSpanSerialization(SerializationTarget.Nanoseconds)]
public TimeSpan Timeout { get; set; }
```
which then gets intercepted in the ContractResolver.

I wanted to avoid coupling the contract too closely with the serializer, and in his initial description @jterry75 mentioned introducing an Attribute, which I interpreted to be "custom" attribute 😄 

I do see your point though; messing with the ContractResolver can be opaque at times. 

'twould be a quick fix to refactor the code to use the ```[JsonConvert(SecondsConverter)]``` instead of the custom attributes if ya'll would rather do it that way.

**Comment by orthros** [comment]
I just filed another pull request that uses the builtin ```[JsonConvert]``` attributes and adds a small enhancement to specgen.

**Comment by jterry75** [comment]
@orthros - This is completed yes? Can we close?

**Comment by orthros** [comment]
Yes it is. Thank you!
